{% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
{% if GIT_DESCRIBE_NUMBER|int != 0 %}
  {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
{% endif %}

package:
  name: img-intake
  version: {{tagged_version}}

source:
  path: ../

build:
  number: 0
  string: py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  run:
    - bioformats
    - dask
    - h5py
    - imageio
    - intake
    - intake-xarray
    - javabridge
    - mrcfile
    - natsort
    - nibabel
    - pydicom
    - pyyaml
    - xarray
    - xmltodict
    - yaml
    - z5py
    - zarr
    - zipfile
    - pip
    - pip:
      - flywheel-sdk
      - imagecodecs
      - pynrrd
      - python-bioformats
